# site settings
title: Nexyon
subtitle:
email: contact@nexyon.dev
description: "Nexyon is a software development company that specializes in web development, mobile development, and cloud computing."
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://nexyon.dev" # the base hostname & protocol for your site, e.g. http://example.com
author: Nexyon
street_address: 9 Avenue Balcons du Front de Mer
city: Canet-en-Roussillon
state: Occitanie
zip_code: 66140
country: France
phone: N/A

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/EssenCiel
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  X-Twitter: https://x.com/essencielapp
  Facebook:
  Slack:
  Threads: https://threads.net/essencielapp

statusPage: https://status.nexyon.dev/status/essenciel

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- all_posts.md
- ELEMENTS.md
- LICENSE.md
- CONTRIBUTING.md
- README.md 
