version: '3.8'
services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '4000:4000'
    environment:
      - JEKYLL_ENV=development
    restart: unless-stopped

networks:
  default:
    driver: bridge
